### ISSUE TITLE
Autosplitter doesn't work on RetroArch with Genesis Plus GX

### ISSUE THREAD

**Issue by amseager** [SonicSpeedrunning/SEGAMasterSplitter#52]
Tried with the latest version of RetroArch (1.9.12).
I tested several games from the list - the autosplitter doesn't work with any of them. But it works if I switched to BlastEm core.
Probably the memoryoffset searching logic has been changed?

**Comment by amseager** [comment]
Found that 0x23EA0 should be added to the `refLocation`

**Comment by beninswe** [comment]
Thanks, I think 0x23EA0 will likely break compatibility, but I have fixed the issue in #53 the memory references we were watching were only 32bit, and it seems like retroarch is now using 64bit ones in a recent version, so have added in support for these.
