### ISSUE TITLE
Retroarch: it's impossible to hot-swap the cores (without exiting and relaunching the emulator) after the first initialization

### ISSUE THREAD

**Issue by amseager** [SonicSpeedrunning/SEGAMasterSplitter#54]
Steps to reproduce:
1. Download both available cores (GPGX and BlastEm) in Retroarch
2. Set the core association to the e.g. GPGX for a game
3. Launch the game and check that autosplitter is working
4. Close the content
5. Set the core association to the other core (BlastEm in this case)
6. Launch the game again
7. Check logs in DebugView: `Retroarch - GPGX` is printed again / autosplitter stops working

Looks like a minor issue though.

**Comment by beninswe** [comment]
Unfortunately, it's an issue with livesplit and caching modules, there is a PR for fixing it here: https://github.com/LiveSplit/LiveSplit/pull/1835 (though I can't guarantee if that gets put into livesplit it will fix this issue automatically though).

**Comment by amseager** [comment]
Ok, thanks for clarifying that
